### ISSUE TITLE
[CI] macOS hdiutil error

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2673]
```
[100%] Generating teeworlds-0.7.5-osx.dmg
hdiutil: create failed - no mountable file systems
Traceback (most recent call last):
  File "/Users/runner/work/teeworlds/teeworlds/scripts/dmg.py", line 108, in <module>
    main()
  File "/Users/runner/work/teeworlds/teeworlds/scripts/dmg.py", line 105, in main
    dmg.create(volume_name=args.volume_name, directory=args.directory, dmg=args.output, symlinks=symlinks)
  File "/Users/runner/work/teeworlds/teeworlds/scripts/dmg.py", line 76, in create
    self._hdiutil('create', '-volname', volume_name, '-srcdir', directory, dmg)
  File "/Users/runner/work/teeworlds/teeworlds/scripts/dmg.py", line 69, in _hdiutil
    self._check_call((self.config.hdiutil,) + args)
  File "/Users/runner/work/teeworlds/teeworlds/scripts/dmg.py", line 28, in _check_call
    subprocess.check_call(process_args, *args, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('/usr/bin/hdiutil', 'create', '-volname', 'teeworlds-0.7.5-osx', '-srcdir', 'pack_teeworlds-0.7.5-osx_dmg', 'teeworlds-0.7.5-osx.dmg')' returned non-zero exit status 1
make[3]: *** [teeworlds-0.7.5-osx.dmg] Error 1
make[2]: *** [CMakeFiles/package_dmg.dir/all] Error 2
make[1]: *** [CMakeFiles/package_default.dir/rule] Error 2
make: *** [package_default] Error 2
```

example run: https://github.com/teeworlds/teeworlds/pull/2542/checks?check_run_id=869760687

**Comment by ChillerDragon** [comment]
Seems to be fixed? Idk what broke or fixed it.
