### ISSUE TITLE
MacOS runs sometimes fail with "hdiutil: create failed - Resource busy" or timeout

### ISSUE THREAD

**Issue by Robyt3** [teeworlds/teeworlds#2956]
Sometimes the MacOS run takes forever or finally fails with the following log:

```
[100%] Generating teeworlds-0.7.5-osx.dmg
hdiutil: create failed - Resource busy
Traceback (most recent call last):
  File "/Users/runner/work/teeworlds/teeworlds/scripts/dmg.py", line 108, in <module>
    main()
  File "/Users/runner/work/teeworlds/teeworlds/scripts/dmg.py", line 105, in main
    dmg.create(volume_name=args.volume_name, directory=args.directory, dmg=args.output, symlinks=symlinks)
  File "/Users/runner/work/teeworlds/teeworlds/scripts/dmg.py", line 76, in create
    self._hdiutil('create', '-volname', volume_name, '-srcdir', directory, dmg)
  File "/Users/runner/work/teeworlds/teeworlds/scripts/dmg.py", line 69, in _hdiutil
    self._check_call((self.config.hdiutil,) + args)
  File "/Users/runner/work/teeworlds/teeworlds/scripts/dmg.py", line 28, in _check_call
    subprocess.check_call(process_args, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('/usr/bin/hdiutil', 'create', '-volname', 'teeworlds-0.7.5-osx', '-srcdir', 'pack_teeworlds-0.7.5-osx_dmg', 'teeworlds-0.7.5-osx.dmg')' returned non-zero exit status 1
```

**Comment by Learath2** [comment]
Here is the fix @heinrich5991 took from CPython: https://github.com/ddnet/ddnet/commit/8fc1fe3811b40f39e13b12aa41abe57ee1c95ece, ddnet/ddnet#3711
