### ISSUE TITLE
Segmentation fault (read) while loading map in CRenderTools::RenderEvalEnvelope, render_map.cpp:148

### ISSUE THREAD

**Issue by mmmds** [teeworlds/teeworlds#2979]
The client crashes when an invalid map ([12.map.zip](https://github.com/teeworlds/teeworlds/files/7402711/12.map.zip)) is loaded. Such a map can be delivered to the client by a malicious server.

Tested on Ubuntu 20.04 x86_64, Teeworlds version: [f35da54b6f2c5f9fd4bbd4559f887ccf8f8cc526](https://github.com/teeworlds/teeworlds/commit/f35da54b6f2c5f9fd4bbd4559f887ccf8f8cc526)

Compilation with ASAN:
```
export CXXFLAGS="-ggdb -O0 -fsanitize=address -fno-omit-frame-pointer"
export CFLAGS="-ggdb -O0 -fsanitize=address -fno-omit-frame-pointer"
cmake ..
make
```

Run and connect to a server that delivers an invalid map:
```
./teeworlds "connect 127.0.0.1" "gfx_fullscreen 0" "gfx_screen_height 240" "gfx_screen_width 360"
[...]
AddressSanitizer:DEADLYSIGNAL
=================================================================
==33664==ERROR: AddressSanitizer: SEGV on unknown address 0x613858d99a28 (pc 0x5555558509b3 bp 0x7fffffffb0e0 sp 0x7fffffffae30 T0)
==33664==The signal is caused by a READ memory access.
    #0 0x5555558509b2 in CRenderTools::RenderEvalEnvelope(CEnvPoint*, int, int, float, float*) /home/osboxes/teeworlds/teeworlds-asan/src/game/client/render_map.cpp:148
    #1 0x5555556f5f50 in CMapLayers::EnvelopeEval(float, int, float*, void*) /home/osboxes/teeworlds/teeworlds-asan/src/game/client/components/maplayers.cpp:245
    #2 0x5555558532cf in CRenderTools::RenderQuads(CQuad*, int, int, void (*)(float, int, float*, void*), void*) /home/osboxes/teeworlds/teeworlds-asan/src/game/client/render_map.cpp:240
    #3 0x5555556f75f1 in CMapLayers::OnRender() /home/osboxes/teeworlds/teeworlds-asan/src/game/client/components/maplayers.cpp:375
    #4 0x555555827989 in CGameClient::OnRender() /home/osboxes/teeworlds/teeworlds-asan/src/game/client/gameclient.cpp:611
    #5 0x5555555fce4e in CClient::Render() /home/osboxes/teeworlds/teeworlds-asan/src/engine/client/client.cpp:796
    #6 0x5555555fce4e in CClient::Run() /home/osboxes/teeworlds/teeworlds-asan/src/engine/client/client.cpp:2131
    #7 0x5555555d24e5 in main /home/osboxes/teeworlds/teeworlds-asan/src/engine/client/client.cpp:2704
    #8 0x7ffff68e10b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #9 0x5555555dc48d in _start (/home/osboxes/teeworlds/teeworlds-asan/build/teeworlds+0x8848d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/osboxes/teeworlds/teeworlds-asan/src/game/client/render_map.cpp:148 in CRenderTools::RenderEvalEnvelope(CEnvPoint*, int, int, float, float*)
==33664==ABORTING
```

Compilation without ASAN:
```
export CXXFLAGS="-ggdb -O0"
export CFLAGS="-ggdb -O0"
cmake ..
make
```

Run and connect to a server that delivers an invalid map:
```
./teeworlds "connect 127.0.0.1" "gfx_fullscreen 0" "gfx_screen_height 240" "gfx_screen_width 360"
[...]
Segmentation fault (core dumped)
```

**Comment by AssassinTee** [comment]
~wasn't able to load this anymore:
`invalid file information: map item size does not match file. type_index=3 item_index=9 size=52 file_size=68`~

**Comment by ChillerDragon** [comment]
I still segfault. On `Linux archlinux 6.16.6-arch1-1` at 5d682733e482950f686663c129adc4b751c8d790

```
[2025-09-23 09:54:24][datafile]: loading data index=12 size=206 uncompressed=368
[2025-09-23 09:54:24][client]: loaded map 'maps/12.map'
[2025-09-23 09:54:24][client/network]: loading done
[2025-09-23 09:54:24][datafile]: loading data index=0 size=22 uncompressed=14
[2025-09-23 09:54:24][datafile]: loading data index=1 size=19 uncompressed=11
[2025-09-23 09:54:24][datafile]: loading data index=2 size=18 uncompressed=10
[2025-09-23 09:54:24][datafile]: loading data index=3 size=12 uncompressed=4
[2025-09-23 09:54:24][datafile]: loading data index=4 size=69 uncompressed=152
[2025-09-23 09:54:24][datafile]: loading data index=5 size=627 uncompressed=2432

Thread 1 "teeworlds" received signal SIGSEGV, Segmentation fault.
CMapLayers::EnvelopeEval (TimeOffset=0, Env=4, pChannels=0x7fffffffa4d0, pUser=0x55555589d700 <gs_MapLayersBackGround>)
    at /home/chilller/Desktop/gaming/teeworlds/src/game/client/components/maplayers.cpp:227
227             float EnvalopTicks = (pItemPoints[pItem->m_NumPoints-1].m_Time - pItemPoints[0].m_Time)/1000.0f * pThis->Client()->GameTickSpeed();
(gdb) bt
#0  CMapLayers::EnvelopeEval (TimeOffset=0, Env=4, pChannels=0x7fffffffa4d0, pUser=0x55555589d700 <gs_MapLayersBackGround>)
    at /home/chilller/Desktop/gaming/teeworlds/src/game/client/components/maplayers.cpp:227
#1  0x000055555564d92b in CRenderTools::RenderQuads
    (this=0x555555992a78, pQuads=0x555557614f70, NumQuads=16, RenderFlags=2, pfnEval=0x5555555d2b68 <CMapLayers::EnvelopeEval(float, int, float*, void*)>, pUser=0x55555589d700 <gs_MapLayersBackGround>) at /home/chilller/Desktop/gaming/teeworlds/src/game/client/render_map.cpp:239
#2  0x00005555555d3cf0 in CMapLayers::OnRender (this=0x55555589d700 <gs_MapLayersBackGround>)
    at /home/chilller/Desktop/gaming/teeworlds/src/game/client/components/maplayers.cpp:378
#3  0x000055555563b797 in CGameClient::OnRender (this=0x5555559778e0) at /home/chilller/Desktop/gaming/teeworlds/src/game/client/gameclient.cpp:614
#4  0x0000555555572bcc in CClient::Render (this=0x7ffff6926010) at /home/chilller/Desktop/gaming/teeworlds/src/engine/client/client.cpp:786
#5  0x0000555555578c0c in CClient::Run (this=0x7ffff6926010) at /home/chilller/Desktop/gaming/teeworlds/src/engine/client/client.cpp:2120
#6  0x000055555557b36d in main (argc=2, argv=0x7fffffffce98) at /home/chilller/Desktop/gaming/teeworlds/src/engine/client/client.cpp:2702
```

**Comment by AssassinTee** [comment]
missed that some of this issues link to teeworlds and not ddnet 🙈
