### ISSUE TITLE
Segmentation fault (read) while parsing map in CMapLayers::LoadEnvPoints, maplayers.cpp:175

### ISSUE THREAD

**Issue by mmmds** [teeworlds/teeworlds#2982]
The client crashes when an invalid map ([15.map.zip](https://github.com/teeworlds/teeworlds/files/7402714/15.map.zip)) is loaded. Such a map can be delivered to the client by a malicious server.

Tested on Ubuntu 20.04 x86_64, Teeworlds version: [f35da54b6f2c5f9fd4bbd4559f887ccf8f8cc526](https://github.com/teeworlds/teeworlds/commit/f35da54b6f2c5f9fd4bbd4559f887ccf8f8cc526)

Compilation with ASAN:
```
export CXXFLAGS="-ggdb -O0 -fsanitize=address -fno-omit-frame-pointer"
export CFLAGS="-ggdb -O0 -fsanitize=address -fno-omit-frame-pointer"
cmake ..
make
```

Run and connect to a server that delivers an invalid map:
```
./teeworlds "connect 127.0.0.1" "gfx_fullscreen 0" "gfx_screen_height 240" "gfx_screen_width 360"
[...]
AddressSanitizer:DEADLYSIGNAL
=================================================================
==33918==ERROR: AddressSanitizer: SEGV on unknown address 0x61f00c1a92b0 (pc 0x5555556fa3c6 bp 0x7ffffffd8ff0 sp 0x7ffffffd8e20 T0)
==33918==The signal is caused by a READ memory access.
    #0 0x5555556fa3c5 in CMapLayers::LoadEnvPoints(CLayers const*, array<CEnvPoint, allocator_default<CEnvPoint> >&) /home/osboxes/teeworlds/teeworlds-asan/src/game/client/components/maplayers.cpp:175
    #1 0x5555556fcf3b in CMapLayers::OnMapLoad() /home/osboxes/teeworlds/teeworlds-asan/src/game/client/components/maplayers.cpp:117
    #2 0x555555839981 in CGameClient::OnConnected() /home/osboxes/teeworlds/teeworlds-asan/src/game/client/gameclient.cpp:459
    #3 0x5555555f6755 in CClient::ProcessServerPacket(CNetChunk*) /home/osboxes/teeworlds/teeworlds-asan/src/engine/client/client.cpp:1283
    #4 0x5555555f91ce in CClient::PumpNetwork() /home/osboxes/teeworlds/teeworlds-asan/src/engine/client/client.cpp:1596
    #5 0x5555555f9596 in CClient::Update() /home/osboxes/teeworlds/teeworlds-asan/src/engine/client/client.cpp:1766
    #6 0x5555555fc1f0 in CClient::Run() /home/osboxes/teeworlds/teeworlds-asan/src/engine/client/client.cpp:2108
    #7 0x5555555d24e5 in main /home/osboxes/teeworlds/teeworlds-asan/src/engine/client/client.cpp:2704
    #8 0x7ffff68e10b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #9 0x5555555dc48d in _start (/home/osboxes/teeworlds/teeworlds-asan/build/teeworlds+0x8848d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/osboxes/teeworlds/teeworlds-asan/src/game/client/components/maplayers.cpp:175 in CMapLayers::LoadEnvPoints(CLayers const*, array<CEnvPoint, allocator_default<CEnvPoint> >&)
==33918==ABORTING
```

Compilation without ASAN:
```
export CXXFLAGS="-ggdb -O0"
export CFLAGS="-ggdb -O0"
cmake ..
make
```

Run and connect to a server that delivers an invalid map:
```
./teeworlds "connect 127.0.0.1" "gfx_fullscreen 0" "gfx_screen_height 240" "gfx_screen_width 360"
[...]
Segmentation fault (core dumped)
```

**Comment by AssassinTee** [comment]
~wasn't able to load this anymore: `E datafile: invalid file information: map item size does not match file. type_index=3 item_index=8 size=1979711540 file_size=52`~

**Comment by ChillerDragon** [comment]
I still segfault. On `Linux archlinux 6.16.6-arch1-1` at 5d682733e482950f686663c129adc4b751c8d790

```
[2025-09-23 09:36:31][client]: loaded map 'maps/15.map'
[2025-09-23 09:36:31][client/network]: loading done
[2025-09-23 09:36:32][datafile]: loading data index=0 size=22 uncompressed=14
[2025-09-23 09:36:32][datafile]: loading data index=1 size=19 uncompressed=11
[2025-09-23 09:36:32][datafile]: loading data index=2 size=18 uncompressed=10
[2025-09-23 09:36:32][datafile]: loading data index=3 size=12 uncompressed=4

Thread 1 "teeworlds" received signal SIGSEGV, Segmentation fault.
0x00005555555d2a74 in CMapLayers::LoadEnvPoints (this=0x55555589d700 <gs_MapLayersBackGround>, pLayers=0x555555978190, lEnvPoints=...)
    at /home/chiller/Desktop/gaming/teeworlds/src/game/client/components/maplayers.cpp:178
178                                     p.m_Time = pEnvPoint_v1->m_Time;
(gdb) bt
#0  0x00005555555d2a74 in CMapLayers::LoadEnvPoints (this=0x55555589d700 <gs_MapLayersBackGround>, pLayers=0x555555978190, lEnvPoints=...)
    at /home/chiller/Desktop/gaming/teeworlds/src/game/client/components/maplayers.cpp:178
#1  0x00005555555d27e5 in CMapLayers::OnMapLoad (this=0x55555589d700 <gs_MapLayersBackGround>)
    at /home/chiller/Desktop/gaming/teeworlds/src/game/client/components/maplayers.cpp:120
#2  0x000055555563ac83 in CGameClient::OnConnected (this=0x5555559778e0) at /home/chiller/Desktop/gaming/teeworlds/src/game/client/gameclient.cpp:460
#3  0x000055555557512b in CClient::ProcessServerPacket (this=0x7ffff6926010, pPacket=0x7fffffffc960)
    at /home/chiller/Desktop/gaming/teeworlds/src/engine/client/client.cpp:1270
#4  0x0000555555576740 in CClient::PumpNetwork (this=0x7ffff6926010) at /home/chiller/Desktop/gaming/teeworlds/src/engine/client/client.cpp:1586
#5  0x0000555555577168 in CClient::Update (this=0x7ffff6926010) at /home/chiller/Desktop/gaming/teeworlds/src/engine/client/client.cpp:1751
#6  0x00005555555789d0 in CClient::Run (this=0x7ffff6926010) at /home/chiller/Desktop/gaming/teeworlds/src/engine/client/client.cpp:2095
#7  0x000055555557b36d in main (argc=2, argv=0x7fffffffce98) at /home/chiller/Desktop/gaming/teeworlds/src/engine/client/client.cpp:2702
```

**Comment by AssassinTee** [comment]
I missed that some issues link to teeworlds and some to ddnet 🙈
